import Head from "next/head";
import { GetServerSideProps, NextPage } from "next";
import client from "@/clients/apollo-client";
import {
  GetFriends,
  GetFriendsQuery,
  GetFriendsQueryVariables,
} from "@/generated/graphql";

type Props = {
  friends: GetFriendsQuery["friend"];
};

const Home: NextPage<Props> = ({ friends }) => {
  console.log(friends);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {friends.map((friend) => (
          <div key={friend.id}>
            <h1 className="text-3xl font-bold underline">{friend.username}</h1>
          </div>
        ))}
        <button className="btn">Button</button>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await client.query<
    GetFriendsQuery,
    GetFriendsQueryVariables
  >({
    query: GetFriends,
  });

  return {
    props: {
      friends: data.friend,
    },
  };
};
