import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import { GetServerSideProps, NextPage } from "next";
import client from "@/clients/apollo-client";
import {
  GetFriends,
  GetFriendsQuery,
  GetFriendsQueryVariables,
} from "@/generated/graphql";

type Props = {
  friends: GetFriendsQuery["friend"];
};

const QUERY = gql`
  query {
    friend {
      id
      name
    }
  }
`;

const Home: NextPage<Props> = ({ friends }) => {
  // const { loading, error, data } = useQuery(QUERY);

  console.log(friends);

  // if (loading) {
  //   return <div>Loading...</div>;
  // }
  // if (error) {
  //   console.error(error);
  //   return <div>Error!</div>;
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {friends.map((friend) => (
          <div key={friend.id}>
            <h1>{friend.name}</h1>
          </div>
        ))}
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await client.query<
    GetFriendsQuery,
    GetFriendsQueryVariables
  >({
    query: GetFriends,
  });

  return {
    props: {
      friends: data.friend,
    },
  };
};
