import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import client from "@/clients/apollo-client";
import { DocumentNode, gql } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

type Data = {
  id: string;
  name: string;
};

export default function Home({
  friends,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  console.log(friends);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {friends?.map((friend: Data) => (
          <div key={friend.id}>
            <h1>{friend.name}</h1>
          </div>
        ))}
      </main>
    </>
  );
}

const QUERY = gql`
  query {
    friend {
      id
      name
    }
  }
`;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return client
    .query({
      query: QUERY,
    })
    .then((d) => {
      return {
        props: { friends: d.data.friend },
      };
    })
    .catch((e) => {
      return {
        props: {},
      };
    });
};
